# Generated by Django 4.2.3 on 2023-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='noticias.categoria'),
        ),
    ]
