# Generated by Django 4.2.3 on 2023-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_objeticos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objeticos',
            new_name='Objetivos',
        ),
    ]
