# Generated by Django 4.2.3 on 2023-07-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_rename_objeticos_objetivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objetivos',
            new_name='Objetivo',
        ),
    ]
